/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-29 01:02:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>영화 예매 사이트</title>\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/default.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script>\n");
      out.write("function pop(){\n");
      out.write("	window.open(\"inc/popup.jsp\", \"pop\", \"width=400,height=500,history=no,resizable=no,status=no,scrollbars=yes,menubar=no\")\n");
      out.write("}\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("	$('#exit-btn').click(function(){\n");
      out.write("		$('.iframe-container').remove();\n");
      out.write("		// 추가된 부분 시작\n");
      out.write("		$('iframe').attr('src', '');\n");
      out.write("		// 추가된 부분 끝\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$('#like').on('click', 'input', function() {\n");
      out.write("		$(this).toggleClass('liked');\n");
      out.write("	});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onLoad=\"javascript:pop()\">\n");
      out.write("	<header>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/top.jsp", out, false);
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<article>\n");
      out.write("<!-- 		<div class=\"iframe-container\"> -->\n");
      out.write("<!-- 			<iframe src=\"https://www.youtube.com/embed/xUDhdCsLkjU?autoplay=1&mute=1&autohide=1\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;\" allowfullscreen></iframe> -->\n");
      out.write("<!-- 			<button id=\"exit-btn\">X</button> -->\n");
      out.write("<!-- 		</div> -->\n");
      out.write("		<div id=\"Sort\">\n");
      out.write("			<a href=\"\"><b>무비차트</b></a>\n");
      out.write("			<a href=\"\">상영예정작</a>\n");
      out.write("			<a href=\"\">관람객순</a>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"boxoffice\">\n");
      out.write("			<img src=\"img/어벤져스인피니티워.jpeg\">\n");
      out.write("			<img src=\"img/스파이더맨노웨이홈.jpeg\">\n");
      out.write("			<img src=\"img/싱글 인 서울.jpeg\">\n");
      out.write("			<img src=\"img/프레디의 피자가게.jpeg\">\n");
      out.write("			<img src=\"img/어벤져스엔드게임.jpeg\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div id=\"like\">\n");
      out.write("			<input type=\"button\" value=\"👍 좋아요\">\n");
      out.write("			<input type=\"button\" value=\"👍 좋아요\">\n");
      out.write("			<input type=\"button\" value=\"👍 좋아요\">\n");
      out.write("			<input type=\"button\" value=\"👍 좋아요\">\n");
      out.write("			<input type=\"button\" value=\"👍 좋아요\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<!-- 추가 기능 -->\n");
      out.write("		<div id=\"advertisement\">\n");
      out.write("			<h3>오늘의 할인 이벤트</h3>\n");
      out.write("			<p>CGV 멤버십 회원에게 50% 할인 혜택 제공</p>\n");
      out.write("			<p>자세한 내용은 이벤트 페이지에서 확인하세요!</p>\n");
      out.write("			<a href=\"event.jsp\">이벤트 페이지 바로가기</a>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</article>\n");
      out.write("	<footer>\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/bottom.jsp", out, false);
      out.write("	\n");
      out.write("	</footer>\n");
      out.write("	<script>\n");
      out.write("	$(document).ready(function() {\n");
      out.write("		$('#exit-btn').click(function(){\n");
      out.write("			alert(\"예고편 종료!\");\n");
      out.write("			$('.iframe-container').remove();\n");
      out.write("			$('iframe').attr('src', '');\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
